In [1]:
%matplotlib inline 
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.mlab as mlab
import os
import seaborn as sns
import pandas as pd
import dabest

from scipy import stats
import scipy.io as sio

In [4]:
os.chdir('LFP-Data/Processed/')
ctrl_lfp = np.load('Ctrl-LFP-40Hz.npy')
variant_lfps = np.load('CA-Variants-LFP-40Hz.npy')
variant_hcn_lfps = np.load('HCN-Variants-LFP-40Hz.npy')
variant_scn_lfps = np.load('SCN-Variants-LFP-40Hz.npy')
variant_combinations_lfps = np.load('Combinations-LFP-40Hz.npy')
gmax_lfps = np.load('Gmax-LFP-40Hz.npy')
ipsc_lfps = np.load('Ipsc-LFP-40Hz.npy')
os.chdir('../../')


os.chdir('PSD-Data/')
ctrl_psd = np.load('Ctrl-PSD-40Hz.npy')
variant_psds = np.load('CA-Variants-PSD-40Hz.npy')
variant_hcn_psds = np.load('HCN-Variants-PSD-40Hz.npy')
variant_scn_psds = np.load('SCN-Variants-PSD-40Hz.npy')
variant_combinations_psds = np.load('Combinations-PSD-40Hz.npy')
gmax_psds = np.load('Gmax-PSD-40Hz.npy')
ipsc_psds = np.load('Ipsc-PSD-40Hz.npy')
freqs = np.load('PSD-40Hz-Frequencies.npy')
os.chdir('../')

deltas = sio.loadmat('collectallmeandeltas_PPIat60.mat')
gains = sio.loadmat('collectallmeangains_PPIat60.mat')

In [21]:
print(deltas['Data'][:,2])

['CACNA1C                         ' 'CACNA1C                         '
 'CACNA1C                         ' 'CACNA1C                         '
 'CACNA1C                         ' 'CACNA1C                         '
 'CACNA1C                         ' 'CACNA1C                         '
 'CACNA1C                         ' 'CACNA1C                         '
 'CACNA1C                         ' 'CACNA1C                         '
 'CACNA1C                         ' 'CACNA1C                         '
 'CACNA1C                         ' 'CACNA1C                         '
 'CACNA1C                         ' 'CACNA1C                         '
 'CACNA1C                         ' 'CACNA1C                         '
 'CACNA1C                         ' 'CACNA1C                         '
 'CACNA1C                         ' 'CACNA1C                         '
 'CACNA1C                         ' 'CACNA1C                         '
 'CACNA1C                         ' 'CACNA1C                         '
 'CACN

In [22]:
# get PPI and delta values
ppis = deltas['Data'][:,0]
ds = deltas['Data'][:,1]

In [48]:
# get indices corresponding to the same variants as I have used

# indices not used CACNA1C (4): 10,14,20,21
indices = []
for i,d in enumerate(deltas['Data']):
    print(d[2])    

    print(i)
    if 'KCN' in d[2]:
        print('no')
    elif 'ATP' in d[2]:
        print('no')
    else:
        indices.append(int(i))
print(indices)
del indices[10]
del indices[13]
del indices[18]
del indices[18]
print(indices)

CACNA1C                         
0
CACNA1C                         
1
CACNA1C                         
2
CACNA1C                         
3
CACNA1C                         
4
CACNA1C                         
5
CACNA1C                         
6
CACNA1C                         
7
CACNA1C                         
8
CACNA1C                         
9
CACNA1C                         
10
CACNA1C                         
11
CACNA1C                         
12
CACNA1C                         
13
CACNA1C                         
14
CACNA1C                         
15
CACNA1C                         
16
CACNA1C                         
17
CACNA1C                         
18
CACNA1C                         
19
CACNA1C                         
20
CACNA1C                         
21
CACNA1C                         
22
CACNA1C                         
23
CACNA1C                         
24
CACNA1C                         
25
CACNA1C                         
26
CACNA1C                         
27
CA

In [49]:
frequencies = [40.0]

n = 256
dt = 0.1
duration = 2000
timepoints = int((duration/dt)/2)
group_average = np.zeros((timepoints,))
fs = 1./dt


time = np.arange(0,timepoints)

u40 = 42
l40 = 38
u20 = 22
l20 = 18
u4  = 6
l4  = 2
u3  = 5
l3  = 1

conn_seeds = np.load('Conn-Seeds.npy')
noise_seeds = np.load('Noise-Seeds.npy')

In [50]:
colors =sns.color_palette(n_colors=5,desat=0.5)
rgbs = np.zeros((5,3))
for i,color in enumerate(colors):
    for j,value in enumerate(color):
        value *= 255
        rgbs[i,j]= value
print(rgbs)

[[ 68.25 112.25 142.75]
 [194.75 130.75  74.25]
 [ 73.   131.    73.  ]
 [170.25  82.75  83.25]
 [147.   124.5  167.5 ]]


In [59]:
forties_ctrl  = np.sum(ctrl_psd[l40:u40])
forties_variants = np.zeros((86,)) 


for j in range(0,76):
    forties_variants[j]  = np.sum(variant_psds[j,l40:u40])

for j in range(0,4):
    forties_variants[j+76]  = np.sum(variant_hcn_psds[j,l40:u40])
    
for j in range(0,6):
    forties_variants[j+80]  = np.sum(variant_scn_psds[j,l40:u40])

print(forties_variants)
gamma_change = forties_variants/forties_ctrl
print(gamma_change)

[313.4970609  313.51582554 312.79245932 333.25330126 312.76678775
 333.6189206  295.35043897 322.76466114 312.99203952 327.41591003
 335.52107063 314.2192356  334.67467966 336.2805883  314.41408563
 335.24191969 313.58237693 335.01662355 313.38115037 334.53247241
 313.40543426 334.36098797 312.89627975 334.39639295 313.27984135
 334.08882555 314.5083974  336.67971867 313.0613431  312.93951905
 312.28269373 323.92823223 311.92310005 325.84655733 312.5383239
 311.67755764 312.27087439 318.37730603 334.75069162 333.46865359
 334.67597468 334.07069934 314.68429834 312.80417365 332.05350751
 312.38568981 332.76872927 314.04851153 335.54911307 313.70770417
 334.18345568 313.350401   312.89858286 310.89485074 316.28917042
 314.54555358 313.76491607 334.55018357 314.33159181 334.81886695
 319.08500982 328.15448027 333.55934328 313.63693886 335.69005143
 314.97673808 335.14129138 324.83022366 331.96215798 313.88263247
 334.28691132 320.99674128 327.80745334 308.22474234 350.16965862
 349.754784

### Calculate correlations

In [60]:
from scipy.stats import pearsonr, spearmanr

In [76]:
# convert to float
ds2 = [float(x) for x in ds[indices]]
ppis2 = [float(x) for x in ppis[indices]]

[0.96511343 0.9651712  0.96294429 1.02593382 0.96286526 1.02705939
 0.90924832 0.99364411 0.9635587  1.00796317 1.03291524 0.96733667
 1.03030959 1.03525344 0.96793653 1.03205586 0.96537608 1.03136228
 0.9647566  1.0298718  0.96483135 1.02934388 0.9632639  1.02945287
 0.96444471 1.02850601 0.96822687 1.03648218 0.96377206 0.96339702
 0.96137495 0.99722622 0.96026793 1.00313186 0.96216192 0.95951202
 0.96133857 0.98013746 1.0305436  1.02659679 1.03031358 1.02845021
 0.96876839 0.96298035 1.0222402  0.96169203 1.02444204 0.96681109
 1.03300157 0.9657619  1.02879734 0.96466193 0.96327099 0.95710242
 0.97370905 0.96834126 0.96593803 1.02992632 0.96768257 1.03075348
 0.98231616 1.01023689 1.02687598 0.96554405 1.03343545 0.96966868
 1.03174607 1.00000303 1.02195898 0.96630043 1.02911583 0.9882015
 1.00916855 0.94888238 1.07801151 1.07673431 0.93252416 0.93246223
 0.99556576 1.03975085 1.00118996 0.99390543 1.00568337 0.99814086
 0.99497434 0.99599193]
[0.000147760311135, 0.000147963340685, 

In [79]:
gamma_delta_pearson_r,gamma_delta_pearson_p = pearsonr(gamma_change,ds2)
gamma_delta_spearman_r,gamma_delta_spearman_p = spearmanr(gamma_change,ds2)

print('Pearson r: {0} p: {1}'.format(gamma_delta_pearson_r,gamma_delta_pearson_p))
print('Spearman r: {0} p: {1}'.format(gamma_delta_spearman_r,gamma_delta_spearman_p))

Pearson r: 0.6828174693106089 p: 4.437535325042008e-13
Spearman r: 0.7057030992027926 p: 3.264951536272099e-14


In [80]:
gamma_ppi_pearson_r,gamma_ppi_pearson_p = pearsonr(gamma_change,ppis2)
gamma_ppi_spearman_r,gamma_ppi_spearman_p = spearmanr(gamma_change,ppis2)

print('Pearson r: {0} p: {1}'.format(gamma_ppi_pearson_r,gamma_ppi_pearson_p))
print('Spearman r: {0} p: {1}'.format(gamma_ppi_spearman_r,gamma_ppi_spearman_p))

Pearson r: -0.36541508054333083 p: 0.0005409976935915331
Spearman r: -0.5350535402613331 p: 1.112803392277118e-07
